name: build
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
      - release/*

  pull_request:
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: nuget/setup-nuget@v1
      - run: nuget restore Sentry.Xamarin.sln
      - uses: microsoft/setup-msbuild@v1.0.2
        if: matrix.os == 'windows-latest'
      - name: Build with MSBuild
        run: msbuild Sentry.Xamarin.sln -p:Configuration=Release
      - name: Build iOS Sample app
        run: msbuild Samples/Sentry.Xamarin.Sample.iOS/Sentry.Xamarin.iOS.csproj
        if: matrix.os == 'macos-latest'
      - name: Build Android Sample app
        run: msbuild Samples/Sentry.Xamarin.Sample.Android/Sentry.Xamarin.Android.csproj
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Sentry.Xamarin.Forms.1.0.0.nupkg
          path: |
            ${{ github.workspace }}/Sentry.Xamarin.Forms/bin/Release/Sentry.Xamarin.Forms.1.0.0.nupkg
